name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test and lint
    runs-on: ubuntu-latest
    env:
      INTEGRATION_DATABASE_URL: ${{ secrets.INTEGRATION_DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.4"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install project dependencies
        run: uv sync --dev

      - name: Run unit tests
        run: uv run pytest tests/unit --cov=src/pyserverless --cov-fail-under=90 --cov-branch --cov-report=term-missing

      - name: Run integration tests
        run: uv run pytest tests/integration
      
      - name: Static type checking
        run: uv run pyright
      
      - name: Run ruff linter
        run: uv run ruff check --fix