name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run pytests with uv
    runs-on: ubuntu-latest
    env:
      UV_PROJECT_ENVIRONMENT: /usr/local # so that uv doesnt create a venv
    

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.4"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install project dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
